/* eslint-disable sort-keys */
/* eslint-disable no-magic-numbers */
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";


export default [
  {files: ["**/*.{js,mjs,cjs,ts}"]},
  {languageOptions: { globals: globals.browser }},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      // [Possible Problems](https://eslint.org/docs/latest/rules/#possible-problems)
      "array-callback-return": "warn",
      "no-constructor-return": "warn",
      "no-duplicate-imports": "error",
      "no-inner-declarations": "warn",
      "no-promise-executor-return": "warn",
      "no-self-compare": "warn",
      "no-template-curly-in-string": "error",
      "no-unmodified-loop-condition": "warn",
      "no-unreachable-loop": "warn",
      "no-use-before-define": "error",
      "no-useless-assignment": "warn",
      "require-atomic-updates": "warn",

      // [Suggestions](https://eslint.org/docs/latest/rules/#suggestions)
      "accessor-pairs": "warn",
      "arrow-body-style": ["warn", "as-needed", { "requireReturnForObjectLiteral": true }],
      "block-scoped-var": "warn",
      "camelcase": "error",
      "capitalized-comments": ["warn", "always"],
      "class-methods-use-this": "warn",
      "complexity": ["warn", 20],
      "consistent-return": "error",
      "consistent-this": ["warn", "that"],
      "curly": "error",
      "default-case": "warn",
      "default-case-last": "warn",
      "default-param-last": "warn",
      "dot-notation": "warn",
      "eqeqeq": "error",
      "func-name-matching": "warn",
      "func-names": ["warn", "always"],
      "grouped-accessor-pairs": "warn",
      "guard-for-in": "warn",
      "id-length": "warn",
      "id-match": ["warn", "^([a-z]|[A-Z])+$"],
      "logical-assignment-operators": "warn",
      "max-classes-per-file": ["warn", 1],
      "max-depth": ["warn", 4],
      "max-lines": ["warn", { "max": 300, "skipBlankLines": true, "skipComments": true }],
      "max-lines-per-function": ["warn", { "max": 50, "skipBlankLines": true, "skipComments": true }],
      "max-nested-callbacks": ["warn", 3],
      "max-params": ["warn", 3],
      "max-statements": ["off", 10],
      "new-cap": "warn",
      "no-alert": "warn",
      "no-array-constructor": "warn",
      "no-bitwise": "warn",
      "no-caller": "error",
      "no-console": "off",
      "no-continue": "warn",
      "no-div-regex": "warn",
      "no-else-return": "warn",
      "no-empty-function": "warn",
      "no-eq-null": "warn",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "warn",
      "no-extra-label": "warn",
      "no-implicit-coercion": "warn",
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-inline-comments": "warn",
      "no-invalid-this": "warn",
      "no-iterator": "error",
      "no-label-var": "warn",
      "no-labels": "warn",
      "no-lone-blocks": "warn",
      "no-lonely-if": "warn",
      "no-loop-func": "warn",
      "no-magic-numbers": "error",
      "no-multi-assign": "warn",
      "no-multi-str": "warn",
      "no-negated-condition": "warn",
      "no-nested-ternary": "warn",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "warn",
      "no-object-constructor": "warn",
      "no-octal-escape": "error",
      "no-param-reassign": "warn",
      "no-plusplus": "off",
      "no-proto": "error",
      "no-return-assign": "warn",
      "no-script-url": "error",
      "no-sequences": "warn",
      "no-shadow": "warn",
      "no-ternary": "off",
      "no-throw-literal": "error",
      "no-undef-init": "warn",
      "no-undefined": "error",
      "no-underscore-dangle": "warn",
      "no-unneeded-ternary": "warn",
      "no-useless-call": "warn",
      "no-useless-computed-key": "warn",
      "no-useless-concat": "warn",
      "no-useless-constructor": "warn",
      "no-useless-rename": "warn",
      "no-useless-return": "warn",
      "no-var": "error",
      "no-void": "warn",
      "no-warning-comments": "off",
      "object-shorthand": "warn",
      "operator-assignment": "warn",
      "prefer-arrow-callback": "warn",
      "prefer-const": "warn",
      "prefer-exponentiation-operator": "warn",
      "prefer-named-capture-group": "warn",
      "prefer-numeric-literals": "warn",
      "prefer-object-has-own": "warn",
      "prefer-object-spread": "warn",
      "prefer-promise-reject-errors": "warn",
      "prefer-regex-literals": "warn",
      "prefer-rest-params": "warn",
      "prefer-spread": "warn",
      "prefer-template": "warn",
      "radix": "warn",
      "require-await": "warn",
      "require-unicode-regexp": "warn",
      "sort-imports": "warn",
      "sort-keys": "warn",
      "sort-vars": "warn",
      "symbol-description": "warn",
      "vars-on-top": "warn",
      "yoda": "warn"
    }
  }
];